# -*- mode: conf; -*-

top-title: 临高启明

author:
  name: larryli
  email: larryli@qq.com
  github: larryli

markdown: rdiscount
permalink:  none
production_url: https://larryli.github.io/lingaoqiming.github.com/
img_url: https://larryli.github.io/lingaoqiming.github.com/images

collections:
  characters:
    output: true
